setw -g mode-keys vi
set-window-option -g mode-keys vi
set -g mode-keys vi

set-option -s set-clipboard off
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

# Reload the changes
bind-key r source-file ~/.tmux.conf \; display-message "reloaded"

# set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @tokyo-night-tmux_window_id_style sub
# set -g @tokyo-night-tmux_pane_id_style sub
# set -g @tokyo-night-tmux_zoom_id_style sub
# set -g @tokyo-night-tmux_transparent 1  # 1 or 0
# set -g @tokyo-night-tmux_show_path 1
# set -g @tokyo-night-tmux_show_netspeed 1
# set -g @tokyo-night-tmux_netspeed_iface "eth0" # Detected via default route
# set -g @tokyo-night-tmux_netspeed_showip 1      # Display IPv4 address (default 0)
# set -g @tokyo-night-tmux_netspeed_refresh 1     # Update interval in seconds (default 1)

# For when we don't need to status bar
# set -g status off

# Disable all status information
# set -g status-interval 0
# set -g status-justify left
set -g status-fg white
set -g status-bg default
set-option -g status-style bg=default
# set -g status-left-length 10
# set -g status-right-length 0
#
# # Show only a single asterisk as indicator
# set -g status-left '* '
#
# # Hide everything else
# set -g status-right ''
# set -g window-status-format ''
# set -g window-status-current-format ''
# set -g status-style bg=black,fg=white
#
# # Optional: remove visual noise
# set -g pane-border-status off
# set -g message-style bg=black,fg=white

set -g prefix C-space

# reload config file (change file location to your the tmux.conf you want to use)
# unbind r
# bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# split panes using - and _
unbind '"'
unbind %
bind _ split-window -h
bind - split-window -v

# mouse on
set -g mouse on

# Vim-Style Keybinding for Window Swapping
# bind -r p last-window
bind -r o new-window
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# to fix delay between switching in nvim
set -sg escape-time 5

# List of plugins
set -g @plugin 'tmux-plugins/tpm' # plugin manager
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'niksingh710/minimal-tmux-status'

#move status bar to top
# set-option -g status-position top
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# add sessionizer plugin?

# Color-Themes
# set -g @plugin 'theutz/tmux-tokyonight-nvim'
# set -g @plugin 'catppuccin/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
